apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  host: postgres
  user: postgres
  password: postgres
  sslmode: prefer
  caCert: ""
  url: postgresql://postgres:postgres@postgres:5432/pgvs3
  metastoreUrl: postgresql://postgres:postgres@postgres:5432/quickwit_metastore
